# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160616_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='video_url',
        ),
        migrations.AddField(
            model_name='chapter',
            name='duration',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='start_time',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
