# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20160625_1732'),
        ('mainapp', '0003_chapter_name'),
    ]

    operations = [
    ]
