# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.models
import mainapp.utils.pathutil


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(null=True, upload_to=mainapp.utils.pathutil.user_chapter_path),
        ),
    ]
