# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20160626_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='additional_content',
        ),
        migrations.AddField(
            model_name='additionalcontent',
            name='pictures_array',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='additionalcontent',
            name='textblocks_array',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='additionalcontent',
            name='type',
            field=models.IntegerField(choices=[(0, 'Video'), (1, 'Images and Text')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalcontent',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
