# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20160628_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='additionalcontent',
            name='video',
            field=models.FileField(null=True, upload_to=mainapp.models.AdditionalContent.user_video_path),
        ),
    ]
