# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_additionalcontent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcontent',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
