# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20160706_2037'),
        ('mainapp', '0007_auto_20160706_1931'),
    ]

    operations = [
    ]
