# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='preview_image',
            field=models.ImageField(default=42, upload_to=''),
            preserve_default=False,
        ),
    ]
