# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.utils.pathutil


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_chapter_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preview_type',
            field=models.IntegerField(choices=[(0, 'Video'), (1, 'Image Text')], default=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='preview_video',
            field=models.FileField(null=True, upload_to=mainapp.utils.pathutil.user_preview_video_path),
        ),
    ]
