# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.utils.pathutil


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20160713_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.utils.pathutil.user_preview_video_path),
        ),
    ]
