# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20160713_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='preview_type',
            field=models.IntegerField(choices=[(0, 'Video'), (1, 'Images')]),
        ),
    ]
