# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.utils.pathutil


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20160713_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='preview_image',
            field=models.ImageField(upload_to=mainapp.utils.pathutil.user_chapter_path),
        ),
    ]
