# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.utils.pathutil


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20160713_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='preview_text',
        ),
        migrations.AddField(
            model_name='additionalcontent',
            name='description',
            field=models.CharField(default=42, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalcontent',
            name='image',
            field=models.ImageField(default=42, upload_to=mainapp.utils.pathutil.user_chapter_layer_path),
            preserve_default=False,
        ),
    ]
